### ISSUE TITLE
UnicodeDecodeError at 'stg refresh'

### ISSUE THREAD

**Issue by mbert** [ctmarinas/stgit#21]
Sometimes I run into the exception shown below. Unfortunately this happens in a rather large project and I have not yet been able to find out which file causes this. However this error should of course not happen. After the exception has been shown, I find my commit in 'refresh-temp'. I am unable to squash the commit with the one I had originally wanted to update with the same error.

It is worthwhile mentioning that this problem has started to occur after upgrading from stg 0.17 to **stg 0.18**. It has happened on different Linux systems with different Python versions (currently I am using Python 2.7.14 on a Fedora 27 system). Temporarily downgrading to stg 0.17 helps in such a situation, I can then cleanly squash, refresh or whatever it is I want. 

        Error: Unhandled exception:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/stgit/main.py", line 194, in _main
            ret = command.func(parser, options, args)
          File "/usr/lib/python2.7/site-packages/stgit/commands/refresh.py", line 267, in func
            stack, patch_name, paths, temp_index = path_limiting)
          File "/usr/lib/python2.7/site-packages/stgit/commands/refresh.py", line 140, in make_temp_patch
            print_current_patch = False), temp_name
          File "/usr/lib/python2.7/site-packages/stgit/lib/transaction.py", line 272, in run
            write(self.__msg)
          File "/usr/lib/python2.7/site-packages/stgit/lib/transaction.py", line 269, in write
            log.log_entry(self.__stack, msg)
          File "/usr/lib/python2.7/site-packages/stgit/lib/log.py", line 341, in log_entry
            new_log.write_commit()
          File "/usr/lib/python2.7/site-packages/stgit/lib/log.py", line 296, in write_commit
            tree = self.__tree(metadata)
          File "/usr/lib/python2.7/site-packages/stgit/lib/log.py", line 290, in __tree
            patches = dict((pn, pf(c)) for pn, c in self.patches.items())
          File "/usr/lib/python2.7/site-packages/stgit/lib/log.py", line 290, in <genexpr>
            patches = dict((pn, pf(c)) for pn, c in self.patches.items())
          File "/usr/lib/python2.7/site-packages/stgit/lib/log.py", line 288, in pf
            r = patch_file(self.__repo, c.data)
          File "/usr/lib/python2.7/site-packages/stgit/lib/log.py", line 132, in patch_file
            repo.diff_tree(cd.parent.data.tree, cd.tree, ['-M']).strip(),
          File "/usr/lib/python2.7/site-packages/stgit/lib/git.py", line 832, in diff_tree
            t1.sha1, t2.sha1)
          File "/usr/lib/python2.7/site-packages/stgit/lib/git.py", line 676, in diff_trees
            s = data.decode('utf-8')
          File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
            return codecs.utf_8_decode(input, errors, True)
        UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 1356: invalid start byte

**Comment by jpgrayson** [comment]
Thank you for this bug report @mbert. I am able to reproduce the issue.

I believe trying to refresh with any changed files containing non-utf-8 encoded text will trigger this. This is an ugly regression. Apologies for that.

I will be working on this. I believe the solution will require stgit to keep diff and blob data as binary (`bytes` not `unicode` or Python 3 `str`) from end-to-end.
