### ISSUE TITLE
setup.py installation broken under Fedora30

### ISSUE THREAD

**Issue by jnsnow** [ctmarinas/stgit#37]
Running:

```
> python3 setup.py install --user
```

appears to produce a broken installation:

```
jhuston@probe (master) ~/s/stgit> which stg
/home/bos/jhuston/.local/bin/stg
jhuston@probe (master) ~/s/stgit> stg --help
Traceback (most recent call last):
  File "/home/bos/jhuston/.local/bin/stg", line 51, in <module>
    from stgit.main import main
  File "/home/bos/jhuston/.local/lib/python3.7/site-packages/stgit/main.py", line 15, in <module>
    from stgit import argparse, run, utils
  File "/home/bos/jhuston/.local/lib/python3.7/site-packages/stgit/argparse.py", line 20, in <module>
    from stgit.lib.git import Date
ModuleNotFoundError: No module named 'stgit.lib.git'
```

It doesn't look like it installs anything under lib/git:

```
jhuston@probe (master) ~/s/stgit> ls ~/.local/lib/python3.7/site-packages/stgit/lib
edit.py  __init__.py  log.py  objcache.py  __pycache__/  stack.py  stackupgrade.py  transaction.py
```

Editing the setup.py configuration appears to fix it:

```
diff --git a/setup.py b/setup.py
index 264a58b..1cc8936 100755
--- a/setup.py
+++ b/setup.py
@@ -110,7 +110,10 @@ setup(
     description='Stacked GIT',
     long_description='Push/pop utility on top of GIT',
     scripts=['stg'],
-    packages=list(map(str, ['stgit', 'stgit.commands', 'stgit.lib'])),
+    packages=list(map(str, ['stgit',
+                            'stgit.commands',
+                            'stgit.lib',
+                            'stgit.lib.git'])),
     data_files=[
         ('share/stgit/templates', glob('stgit/templates/*.tmpl')),
         ('share/stgit/examples', glob('examples/*.tmpl')),
```

**Comment by lkraav** [comment]
I can confirm, same thing happens here.

**Comment by jpgrayson** [comment]
Repaired in #38 (d0dcf0ee3466f869d122a1044c9d25cfc1954bc9).
