### ISSUE TITLE
0.19-80-g114b-dirty: `stg pick` fails when target commit has an empty commit message

### ISSUE THREAD

**Issue by lkraav** [ctmarinas/stgit#39]
Empty commit messages can occur for example with `stg import /some/patch.diff`.

Then. from another branch:

```
$ stg pick 2ea43760dc34
Checking for changes in the working directory ... done                                               
Importing commit 2ea43760dc3491e79b67e50eefb3ad13faed6d9b ... 
  Pushing patch "None" ... warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1699 and retry the command.
done (conflict)                                                                                           
Error: 1 merge conflict(s)                
       CONFLICT (content): Merge conflict in Kconfig                                                                                                                                                                 
Error: Unhandled exception:         
Traceback (most recent call last):                                                                        
  File "/home/leho/.local/lib64/python3.6/site-packages/stgit/main.py", line 202, in _main
    ret = command.func(parser, options, args)                                                             
  File "/home/leho/.local/lib64/python3.6/site-packages/stgit/commands/pick.py", line 314, in func
    stack, ref_stack, iw, commit, patchname, options                                                      
  File "/home/leho/.local/lib64/python3.6/site-packages/stgit/commands/pick.py", line 242, in __pick_commit
    retval = trans.run(iw, print_current_patch=False)                                                                                                                                                                
  File "/home/leho/.local/lib64/python3.6/site-packages/stgit/lib/transaction.py", line 311, in run
    write(self.__msg + ' (CONFLICT)')                                                                     
  File "/home/leho/.local/lib64/python3.6/site-packages/stgit/lib/transaction.py", line 301, in write
    self.__stack.patches.new(pn, commit, msg)                                                                                                                                                                        
  File "/home/leho/.local/lib64/python3.6/site-packages/stgit/lib/stack.py", line 231, in new
    p.set_commit(commit, msg)                                                                                                                                                                                        
  File "/home/leho/.local/lib64/python3.6/site-packages/stgit/lib/stack.py", line 112, in set_commit
    self.__write_compat_files(commit, msg)                                                                
  File "/home/leho/.local/lib64/python3.6/site-packages/stgit/lib/stack.py", line 82, in __write_compat_files                            
    write('authname', d.author.name)
  File "/home/leho/.local/lib64/python3.6/site-packages/stgit/lib/stack.py", line 61, in write                                                                                                                       
    fn = os.path.join(self.__compat_dir, name)                                                                                                                                                                       
  File "/home/leho/.local/lib64/python3.6/site-packages/stgit/lib/stack.py", line 56, in __compat_dir
    return os.path.join(self.__stack.directory, 'patches', self.__name)                                                                                                                                              
  File "/usr/lib/python-exec/python3.6/../../../lib64/python3.6/posixpath.py", line 94, in join                                                                                                                      
    genericpath._check_arg_types('join', a, *p)                                                                                                                                                                      
  File "/usr/lib/python-exec/python3.6/../../../lib64/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None   
TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by jpgrayson** [comment]
Thank you @lkraav for this bug report.

I was able to reproduce and repair the problem.
