### ISSUE TITLE
stg import -m fails when subject contains a colon followed by a space.

### ISSUE THREAD

**Issue by kleikamp** [ctmarinas/stgit#53]
Stacked GIT 0.22
Attempting "stg import -m <patchfile>" when the subject of the patch contains a colon followed by a space results in:

```Checking for changes in the working directory ... done
Error: Unhandled exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/stgit/main.py", line 195, in _main
    ret = command.func(parser, options, args)
  File "/usr/lib/python3.8/site-packages/stgit/commands/imprt.py", line 498, in func
    __import_mail(filename, options)
  File "/usr/lib/python3.8/site-packages/stgit/commands/imprt.py", line 355, in __import_mail
    __import_mail_path(mail_path, filename, options)
  File "/usr/lib/python3.8/site-packages/stgit/commands/imprt.py", line 394, in __import_mail_path
    mailinfo = dict(line.split(b': ') for line in mailinfo_lines if line)
ValueError: dictionary update sequence element #2 has length 3; 2 is required
```
This patch fixes the problem:
```
diff --git a/stgit/commands/imprt.py b/stgit/commands/imprt.py
index aa4a27238cca..6a7213f391aa 100644
--- a/stgit/commands/imprt.py
+++ b/stgit/commands/imprt.py
@@ -391,7 +391,7 @@ def __import_mail_path(mail_path, filename, options):
         'git', 'mailinfo', msg_path, patch_path
     ).encoding(None).decoding(None).raw_input(mail).output_lines(b'\n')
 
-    mailinfo = dict(line.split(b': ') for line in mailinfo_lines if line)
+    mailinfo = dict(line.split(b': ', 1) for line in mailinfo_lines if line)
 
     with open(msg_path, 'rb') as f:
         msg_body = f.read()
```

**Comment by jpgrayson** [comment]
Thanks for the bug report. And for the repair suggestion. I have pushed a commit with the repair along with updated test cases to catch the problem.

I will make a v0.23 release in the near future with this repair and some other minor changes.

Closing.

**Comment by kleikamp** [comment]
Thanks for the quick response!
